### ISSUE TITLE
Some questions..

### ISSUE THREAD

**Issue by twwhung** [williamw520/jsoda#1]
Hello! Great Job!

I used SimpleDB with PHP before and now need with Java. I am really interesting in your project.
My question is as you say jsoda does not support  "or condition" in query. 
What should I do when I really need this? Is there a way I can directly set the querystring like "Select  \* from k wher a ='1' or a = '2' " ? 

Thanks for reply!

**Comment by williamw520** [comment]
Hi,

The OR condition really is just a union of multiple queries.  E.g. select *
from k where a = 1 or a = 2 is really just (select \* from k where a = 1)
union (select \* from k where a = 2).  That means you just run the query
twice with different parameter for 'a' and combine the result sets yourself
afterward.  DynamoDB doesn't support OR anyway and Jsoda doesn't want to
add complexity beyond what's supported underneath.

Best,

William

On Wed, May 16, 2012 at 3:16 AM, BangBoy <
reply@reply.github.com

**Comment by twwhung** [comment]
Thanks for reply. 
So I guess it does not support "INTERSECTION" condition for SimpleDB, too ? Maybe it would be better if I can directly set query string in some cases. Sorry that I ask so much. I really like ur lib so want to make sure it can fit my need.

Thanks again!

**Comment by williamw520** [comment]
No problem at all for asking.  That's the only way I can gauge user
interest and feature request.

Honestly I don't know the the difference between the Intersection operator
and the And operator.  It seems both produce the same result.

If there are sufficient interest, I can add some client side query
processing to handle Or or Intersection operators.  DynamoDB needs client
side emulation.

On Wed, May 16, 2012 at 8:04 PM, BangBoy <
reply@reply.github.com

**Comment by twwhung** [comment]
Thanks for reply.

"INTERSECTION" is used when it comes to multi-attributes. For example you can not use tag = "a" and tag = "b" if you want something with tag a and tag b.

By the way how do I do with multi-attributes, currently I don't know how to declare a class with multi-attributes or put object with replace = false. 
Or it has not supported it yet ?

Thank you!

**Comment by williamw520** [comment]
I see.

SimpleDB's multi-value attribute is not supported currently.  Put's
attribute Replace flag is set to true to disable multi-value append.  I
always had doubt about the use of multi-value attribute.  It has complex
update semantic and easy to accidentally add extra values.  When a model
object is updated in Jsoda, all the fields are written out.  If a field is
marked as multi-value attribute, it can't tell if it's the first time the
value is created or if it's a update of an existing value which would
append extra undesired values.  The creation should let put go through but
existing update should not let put go through.  It's difficult to say what
a multi-value attribute update is.

Instead I just added support for JSON'ified of complex Java field including
array, which can hold multiple values on an attribute.  That has a very
clear update semantic, i.e. the whole array is replaced at every update.
The only downside is the lack of query support on the JSON field.

On Wed, May 16, 2012 at 11:44 PM, BangBoy <
reply@reply.github.com

**Comment by twwhung** [comment]
Hello 

Currently I have introduce jsoda to my current project and it works pretty well. Here are some questions I want to ask.

1.As SimpleDB's batchput only can be within up to 25 items, currently when items are more than 25 items I break down them by myself. Should this issue be handled in jsoda?
2. Has jsoda already handled sql injection for select operation? Sorry I do not trace code about it clearly.

Finally, I still hope someday multi-value attribute can be supported although it really has some defects. After all , it is one of things of SimpleDB different from Relational DB.

Thank you very much. I really like jsoda . It reduce so many work of mine.

**Comment by williamw520** [comment]
Good idea.  I'll add handling of the batchPut in next release.

All parameter values are quoted via SimpleDBUtils.quoteValue().  I hope the
AWS method escapes the value properly to avoid sql injection.  DynamoDB
only accepts parameter binding via API so there's no chance of sql
injection.

I'll come up with a design to address multi-value problem and add support
for it.

On Tue, May 22, 2012 at 7:40 PM, BangBoy <
reply@reply.github.com
